### ISSUE TITLE
同步过程中出错

### ISSUE THREAD

**Issue by 463419442** [alibaba/MongoShake#297]
![image](https://user-images.githubusercontent.com/59985198/75736374-ff896400-5d37-11ea-8251-64f82bcebfca.png)

 [CRIT] [executor.(*Executor).execute:97] Replayer-3, executor-3, oplog for namespace[db.table] op[i] failed. error type[*mgo.BulkError], error[WiredTigerIndex::insert: key too large to index, failing  2080
mongo版本4.2.
shake版本2.2

**Comment by vinllen** [comment]
4.1.3之后放开key大小为1M的限制，用户的源是4.2，目的是3.4版本，所以同步过程中插入数据，key太大导致index build失败了。
https://jira.mongodb.org/browse/SERVER-36278
3.4版本你可以试一下这里说的方法，看看能不能放开：
https://stackoverflow.com/questions/38815451/mongodb-exception-wiredtigerindexinsert-key-too-large-to-index
官网说明：
https://docs.mongodb.com/v3.4/reference/parameters/

In MongoDB 2.6, if you attempt to insert or update a document so that the value of an indexed field is longer than the Index Key Length Limit, the operation will fail and return an error to the client. In previous versions of MongoDB, these operations would successfully insert or modify a document but the index or indexes would not include references to the document.
To avoid this issue, consider using hashed indexes or indexing a computed value. **If you have an existing data set and want to disable this behavior so you can upgrade and then gradually resolve these indexing issues, you can use failIndexKeyTooLong to disable this behavior.**
failIndexKeyTooLong defaults to true. When false, a 2.6 mongod instance will provide the 2.4 behavior.
Issue the following command to disable the index key length validation:
```
db.adminCommand( { setParameter: 1, failIndexKeyTooLong: false } )
```

官方建议这个忽略了以后要升级，单纯忽略这个会不会有别的影响你可以再关注一下。

**Comment by 463419442** [comment]
已解决，谢谢。
