### ISSUE TITLE
Is there any way to sync data from 1 mongo to 3 or more mongo and from 1 mongoshake process ?

### ISSUE THREAD

**Issue by kdrustun** [alibaba/MongoShake#590]
Hi,

I have 3 questions.

1. Question 

I installed mongoshake process and if i wanna sync 1 to 1 everything is perfect. 
if I wanna sync 1 to 1 from different port and different mongoshake process everything is fine. 
But i wanna sync data from 1 mongo to 3 or more mongo with 1 mongoshake process.

Source: 
sourcemongo:27017

Target:
targetmongo1:27017
targetmongo2:27017
targetmongo3:27017

is there any way to sync data from sourcemongo to 3 target mongo with 1 mongoshake process ? 
What did i do the collector.conf file for this ? 

2. Question

I wanna sync data bi-directionally. Let's say we have a to mongodb server A and B. I wanna sync data from A to B and B to A. 
What is the correct way ? Should i deploy mongoshake to 2 server and sync eachother ?

3. Question

I have 3 mongodb servers A , B and C. I wanna sync data between this 3 servers bi-directionally and from same dbs. 

A to B
A to C
B to A
B to C
C to A
C to B

I deployed 2 mongoshake process on each server and configure like this. Everything works but after a while i'm getting below error. 

syncer oplog collection capped error users should fix it manually

Could you please help me how can i do this ? 

Thanks.

**Comment by vinllen** [comment]
1. MongoShake for direct tunnel only supports from 1 to 1 sync. However, you can use like kafka tunnel to fetch oplog and send to kafka, then you can write code to consume oplog from kafka and then inject it into your different targets. It's not recommend because you should write code which is not simple.
2. For bi-directionally sync, MongoShake needs MongoDB kernel supports, so in Alibaba cloud, we modify MongoDB code to add [gid](https://github.com/alibaba/MongoShake#global-id) to avoid loop problem. It's hard to run bi-directionally sync without gid supports.
3. For capped error, checkout this [issue](https://github.com/alibaba/MongoShake/wiki/FAQ#q-what-does-oplog-collection-capped-error-users-should-fix-it-manually-error-mean)

**Comment by kdrustun** [comment]
Thanks vinllen :)

**Comment by kdrustun** [comment]
Hi vinllen,
My main problem is below,
For example our configuration is from A to B, and from B to C. 
A --> B --> C

If i add a data to A, i'm waiting to see this data to only B. Not C. I think the data shouldn't go to C. 

But this data is going to C over B. 

Could i explain ? 
is there any way to configure like this ?

**Comment by kdrustun** [comment]
And my second problem is below.
I changed the incr_sync.mongo_fetch_method to change_stream to oplog.  I'm using mongodb 4.4.
What is the change_stream exactly? I think explanation is not enough in the collector.conf

[2021/06/28 11:00:27 +03] [EROR] Syncer[rs0] change_stream internal error: client[mongodb://username:password@127.0.0.1:27017] create change stream handler failed[(ChangeStreamHistoryLost) Resume of change stream was not possible, as the resume point may no longer be in the oplog.]
[2021/06/28 11:00:27 +03] [CRIT] Syncer[rs0] I can't handle this error, please solve it manually!
